import { useState } from 'react';
import { Bookmark, Check, Trash2, ArrowUpRight } from 'lucide-react';
import { SRI_LANKA_DISTRICTS } from '../data/sriLankaDistricts';
import { type DistrictSnapshot } from '../services/weatherService';
import { RiskBadge } from '../components/common/Status';
import { KEY, readSavedPlaces } from '../services/watchlist';
export default function RegistrationView({ snapshot, onNavigateToMap }: { snapshot: DistrictSnapshot | null; onNavigateToMap: (id: string) => void }) {
  const [saved, setSaved] = useState(readSavedPlaces); const [district, setDistrict] = useState('colombo'); const [message, setMessage] = useState('');
  const persist = (next: string[]) => { try { localStorage.setItem(KEY, JSON.stringify(next)); setSaved(next); setMessage('Saved on this browser.'); } catch { setMessage('Browser storage is unavailable. Your selection could not be saved.'); } };
  const forget = () => { try { localStorage.removeItem(KEY); localStorage.removeItem('floodsentinel_citizen_profile'); setSaved([]); setMessage('Local preferences and any legacy profile have been removed.'); } catch { setMessage('Could not access browser storage.'); } };
  return <div className="saved-layout"><section className="card"><div className="large-icon"><Bookmark size={28} /></div><span className="eyebrow">YOUR DISTRICTS</span><h2>Keep places close.</h2><p className="muted">Save districts for a quicker check-in. Preferences stay on this browser; no phone number or address is collected.</p><label htmlFor="save-district" className="field-label">Choose a district</label><select id="save-district" value={district} onChange={e => setDistrict(e.target.value)}>{SRI_LANKA_DISTRICTS.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="button full" onClick={() => persist([...new Set([...saved, district])])}><Check size={16} />Save district</button><p role="status" className="muted">{message}</p><div className="info-note">This is a local watchlist. SMS, WhatsApp, background notifications and account registration are not connected.</div><button className="text-button" onClick={forget}><Trash2 size={14} />Clear local data, including the old profile</button></section>
    <section className="card"><div className="card-heading"><h2>Saved places</h2><span className="count-badge">{saved.length}</span></div>{saved.length === 0 && <div className="empty-state"><Bookmark size={30} /><h3>A place to start</h3><p>Save your home district or somewhere you care about.</p></div>}{saved.map(id => { const d = SRI_LANKA_DISTRICTS.find(x => x.id === id)!; const reading = snapshot?.districts.find(t => t.id === id); return <div className="saved-row" key={id}><div><h3>{d.name}</h3><p className="muted">{d.province} · {d.riverBasin}</p><RiskBadge level={reading?.risk_tier} /></div><div className="row-actions"><button className="icon-button" aria-label={`Open ${d.name}`} onClick={() => onNavigateToMap(id)}><ArrowUpRight size={18} /></button><button className="icon-button" aria-label={`Remove ${d.name}`} onClick={() => persist(saved.filter(x => x !== id))}><Trash2 size={16} /></button></div></div>; })}</section></div>;
}
